name: Apna Chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1


environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For using cupertino icons
  cupertino_icons: ^1.0.8

  # For integrating firebase
  firebase_core: ^3.0.0

  # For handling firebase authentication
  firebase_auth: ^5.0.0

  # For handling google sign in
  google_sign_in: ^6.2.1

  # For accessing cloud firestore database
  cloud_firestore: ^5.0.0

  # For showing network images
  cached_network_image: ^3.3.1

  # For picking images
  image_picker: ^1.1.2

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^12.0.0

  # For showing Emojis
  emoji_picker_flutter: ^2.2.0

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^15.0.0

  # Bearer Token for Push Notification
  googleapis_auth: ^1.6.0

  # For calling RestAPIs
  http: ^1.2.1

  # For creating notification channel
  flutter_notification_channel: ^3.1.0

  # For storing images into gallery
  gallery_saver_updated: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #   flutter_launcher_icons: "^0.10.0"

  # flutter_icons:
  #   android: "ic_launcher"
  #   ios: true
  #   image_path: "images/icon.png"
  #   min_sdk_android: 21
  #   remove_alpha_ios: true

  # For recommended coding practices
  flutter_lints: ^4.0.0

flutter:
  # For enabling material design
  uses-material-design: true

  # App Assets
  assets:
    - images/